[build]
builder = "dockerfile"
dockerfilePath = "./WebApp/WebApp/Dockerfile"

[deploy]
# Run database migrations before starting the application
preDeployCommand = ["dotnet ef database update --project WebApp/WebApp --startup-project WebApp/WebApp"]
startCommand = "dotnet WebApp.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 300

# Environment variables for Railway deployment
[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

# Database connection will use Railway's DATABASE_URL automatically
# Railway will inject: DATABASE_URL, PGHOST, PGPORT, PGUSER, PGPASSWORD, PGDATABASE